export const DEFAULT_DESKTOP_UI_CONFIG = {
  basicConfig: {
    backgroundImageUrl:
      'https://chatbot-demo.g.aitention.com/data-dev/static/new_kiosk_demo_ui/airport/airportDemoBG.png',
    pageTitle: 'Expo - Pantheonlab',
    isNeedPrivacyPolicy: false,
    defaultLanguage: 'en-US',
    isNeedFaceDetection: false,
    isNeedMultipleLanguages: false,
    isNeedHotKey: false,
    isInsideBackground: false,
  },
  chatRoomContentWrapStyle: {
    width: '100%',
    borderRadius: '0px',
    margin: '0px',
    height: '100%',
  },
  chatRoomContentStyle: { height: '100%' },
  chatZoneWrapStyle: {
    margin: '0px',
    height: '100%',
    borderRadius: '0px',
    width: '50%',
    right: '0px',
  },
  chatZoneStyle: {
    backgroundColor: 'transparent',
    height: '100%',
    width: '100%',
    padding: '120px 24px 16px 24px',
    bottom: '32px',
    borderRadius: '0px',
    digitalHumanChatBackgroundColor: '',
    clientChatBackgroundColor: '',
  },
  modelPositionConfig: {
    marginLeft: '-35%',
    transform: 'scale(1)',
    bottom: '0%',
  },
  chatPlaceholderStyle: {
    placeholderId: 1,
    isHideInput: false,
    chatArray: [],
    backgroundColor: 'white',
    titleColor: 'black',
    titleAlign: 'center',
    titleSize: 'auto',
    contentColor: 'black',
    contentAlign: 'left',
    contentSize: 'auto',
  },
  subtitleConfig: { fontColor: 'white', fontSize: 20 },
  subtitleStyleConfig: {
    width: '35%',
    maxHeight: '10%',
    backgroundColor: '#333333',
  },
  skipButtonConfig: { bottom: '48px', right: '48%' },
  widgetConfig: {
    chatZoneStyle: {
      backgroundColor: '#ffffff',
      height: 'calc( 100% - 88px )',
      width: '100%',
      padding: '0px',
      bottom: '0px',
      borderRadius: '16px',
      digitalHumanChatBackgroundColor: '',
      clientChatBackgroundColor: '',
    },
    modelPositionConfig: {
      marginLeft: '0px',
      transform: 'scale(1)',
      bottom: '0%',
    },
    subtitleConfig: { fontColor: 'white', fontSize: 20 },
    subtitleStyleConfig: {
      width: '35%',
      maxHeight: '10%',
      backgroundColor: '#333333',
    },
    skipButtonConfig: {},
  },
  isShowPresenterInfo: false,
  rootBackgroundColor: '#ffffff',
  isShowButtonSet: true,
  isShowInputSectionClearButton: false,
  isShowPresenterIconButtonSet: false,
  isShowInputSectionInputBar: true,
};
