export const TYPE_V1_UI_CONFIG = {
  basicConfig: {
    backgroundImageUrl:
      'https://chatbot-demo.g.aitention.com/data-dev/static/new_kiosk_demo_ui/airport/airportDemoBG.png',
    pageTitle: 'Expo - Pantheonlab',
    isNeedPrivacyPolicy: false,
    defaultLanguage: 'en-US',
    isNeedFaceDetection: false,
    isNeedMultipleLanguages: false,
    isNeedHotKey: false,
    isInsideBackground: true,
  },
  chatRoomContentWrapStyle: {
    width: '40%',
    borderRadius: '43px',
    margin: '0px',
    height: '88%',
    marginTop: '4%',
    marginLeft: '5%',
  },
  chatRoomContentStyle: { height: '100%' },
  chatZoneWrapStyle: {
    margin: '0px',
    height: '100%',
    borderRadius: '0px',
    width: '50%',
    right: '0px',
  },
  chatZoneStyle: {
    backgroundColor: 'transparent',
    height: '100%',
    width: '100%',
    padding: '120px 24px 16px 24px',
    bottom: '32px',
    borderRadius: '0px',
    digitalHumanChatBackgroundColor: '',
    clientChatBackgroundColor: '',
  },
  modelPositionConfig: { marginLeft: '0%', transform: 'scale(1)', bottom: '0%' },
  chatPlaceholderStyle: {
    placeholderId: 1,
    isHideInput: false,
    chatArray: [],
    backgroundColor: 'white',
    titleColor: 'black',
    titleAlign: 'center',
    titleSize: 'auto',
    contentColor: 'black',
    contentAlign: 'left',
    contentSize: 'auto',
  },
  subtitleConfig: { fontColor: 'white', fontSize: 20 },
  subtitleStyleConfig: { width: '35%', maxHeight: '10%', backgroundColor: '#333333' },
  skipButtonConfig: { bottom: '48px', right: '48%' },
  widgetConfig: {
    chatZoneStyle: {
      backgroundColor: '#ffffff',
      height: 'calc( 100% - 88px )',
      width: '100%',
      padding: '0px',
      bottom: '0px',
      borderRadius: '16px',
      digitalHumanChatBackgroundColor: '',
      clientChatBackgroundColor: '',
    },
    modelPositionConfig: { marginLeft: '0px', transform: 'scale(1)', bottom: '0%' },
    subtitleConfig: { fontColor: 'white', fontSize: 20 },
    subtitleStyleConfig: { width: '35%', maxHeight: '10%', backgroundColor: '#333333' },
    skipButtonConfig: {},
  },
  isShowPresenterInfo: false,
  rootBackgroundColor: '#3e456',
  isShowButtonSet: true,
  isShowInputSectionClearButton: false,
  isShowPresenterIconButtonSet: false,
  isShowInputSectionInputBar: true,
};

export const TYPE_V1_RIGHT_UI_CONFIG = {
  basicConfig: {
    backgroundImageUrl:
      'https://chatbot-demo.g.aitention.com/data-dev/static/new_kiosk_demo_ui/airport/airportDemoBG.png',
    pageTitle: 'Expo - Pantheonlab',
    isNeedPrivacyPolicy: false,
    defaultLanguage: 'en-US',
    isNeedFaceDetection: false,
    isNeedMultipleLanguages: false,
    isNeedHotKey: false,
    isInsideBackground: true,
  },
  chatRoomContentWrapStyle: {
    width: '40%',
    borderRadius: '43px',
    margin: '0px',
    height: '88%',
    marginTop: '4%',
    marginLeft: '0%',
    right: '5%',
  },
  chatRoomContentStyle: { height: '100%' },
  chatZoneWrapStyle: {
    margin: '0px',
    height: 'calc(100% - 88px)',
    borderRadius: '24px',
    width: '50%',
    right: '0px',
    left: '48px',
    top: '44px',
  },
  chatZoneStyle: {
    backgroundColor: '#f3f3f3',
    height: '',
    width: '100%',
    padding: '120px 24px 16px 24px',
    bottom: '0px',
    borderRadius: '0px',
    digitalHumanChatBackgroundColor: '',
    clientChatBackgroundColor: '',
  },
  modelPositionConfig: { marginLeft: '0%', transform: 'scale(1)', bottom: '0%' },
  chatPlaceholderStyle: {
    placeholderId: '1',
    isHideInput: true,
    chatArray: [],
    backgroundColor: 'white',
    titleColor: 'black',
    titleAlign: 'center',
    titleSize: 'auto',
    contentColor: 'black',
    contentAlign: 'left',
    contentSize: 'auto',
  },
  subtitleConfig: { fontColor: 'white', fontSize: 20 },
  subtitleStyleConfig: { width: '35%', maxHeight: '10%', backgroundColor: '#333333' },
  skipButtonConfig: { bottom: '48px', right: '48%' },
  widgetConfig: {
    chatZoneStyle: {
      backgroundColor: '#ffffff',
      height: 'calc( 100% - 88px )',
      width: '100%',
      padding: '0px',
      bottom: '0px',
      borderRadius: '16px',
      digitalHumanChatBackgroundColor: '',
      clientChatBackgroundColor: '',
    },
    modelPositionConfig: { marginLeft: '0px', transform: 'scale(1)', bottom: '0%' },
    subtitleConfig: { fontColor: 'white', fontSize: 20 },
    subtitleStyleConfig: { width: '35%', maxHeight: '10%', backgroundColor: '#333333' },
    skipButtonConfig: {},
  },
  isShowPresenterInfo: false,
  rootBackgroundColor: 'white',
  isShowButtonSet: false,
  isShowInputSectionClearButton: true,
  isShowPresenterIconButtonSet: false,
  isShowInputSectionInputBar: true,
};

export const FOR_DEMO_UI_CONFIG = {
  chatRoomContentWrapStyle: {
    width: '100%',
    borderRadius: '0px',
    margin: '0px',
    height: '100%',
  },
  chatRoomContentStyle: { height: '100%' },
  chatZoneWrapStyle: {
    margin: '0px',
    height: '100%',
    borderRadius: '0px',
    width: '100%',
    right: '0px',
  },
  chatZoneStyle: {
    backgroundColor: 'transparent',
    height: '100%',
    width: '100%',
    padding: '120px 24px 16px 24px',
    bottom: '32px',
    borderRadius: '0px',
    digitalHumanChatBackgroundColor: '#cec',
    clientChatBackgroundColor: '#435',
  },
  modelPositionConfig: {
    marginLeft: '0%',
    transform: 'scale(1)',
    bottom: '0%',
  },
  subtitleConfig: {
    fontColor: 'white',
    fontSize: 20,
  },
  subtitleStyleConfig: {
    width: '35%',
    maxHeight: '10%',
    backgroundColor: '#333333',
  },
  skipButtonConfig: {},
  widgetConfig: {
    chatZoneStyle: {
      backgroundColor: '#ffffff',
      height: 'calc( 100% - 88px )',
      width: '100%',
      padding: '0px',
      bottom: '0px',
      borderRadius: '16px',
      digitalHumanChatBackgroundColor: '#435',
      clientChatBackgroundColor: '#cec',
    },
    modelPositionConfig: {
      marginLeft: '0px',
      transform: 'scale(2)',
      bottom: '-40%',
    },
    subtitleConfig: {
      fontColor: 'white',
      fontSize: 20,
    },
    subtitleStyleConfig: {
      width: '35%',
      maxHeight: '10%',
      backgroundColor: '#333333',
    },
    skipButtonConfig: {},
  },
  isShowPresenterInfo: false,
  rootBackgroundColor: '#ffffff',
  isShowButtonSet: true,
  isShowInputSectionClearButton: false,
  isShowPresenterIconButtonSet: false,
};
